version: '3.3'

services: 
    db:
      image: mysql
      restart: always
      command: --init-file /usr/src/proba/cms-application/database.sql
      environment: 
        MYSQL_ROOT_PASSWORD: aesrdht345
      ports: 
        - "3306:3306"
    client:
      image: client
    server:
      image: server
      links: 
        - db
      environment: 
        DB_PORT: 3306
        DB_USERNAME: root
        DB_PASSWORD: aesrdht345
        DB_DATABASE: cms
      ports: 
        - "5000:5000"


